// ============================================================
// js/data-siswa.js
// ✅ DATA RESMI 342 SISWA MPLS INSEKTA 11 (TH. 2026-2027)
//    Sumber: PDF "kelompok MPLS 2026 2027" - SMA Sedes Sapientiae
//    Dipetakan ke 11 Kelompok (A-K)
// ============================================================

export const daftarSiswa = [
  // ==================== KELOMPOK A (32 Siswa) ====================
  { id: "KLP_A_01", doc_id: "KLP_A_01", nomor_absen: "01", nama_lengkap: "Angelica Felicia Mulyono", kelompok: "KELOMPOK A" },
  { id: "KLP_A_02", doc_id: "KLP_A_02", nomor_absen: "02", nama_lengkap: "Citra Airin Marito Batubara", kelompok: "KELOMPOK A" },
  { id: "KLP_A_03", doc_id: "KLP_A_03", nomor_absen: "03", nama_lengkap: "Eleora Elafohwe Basa Wilson", kelompok: "KELOMPOK A" },
  { id: "KLP_A_04", doc_id: "KLP_A_04", nomor_absen: "04", nama_lengkap: "Erlangga Danendra Hutagaol", kelompok: "KELOMPOK A" },
  { id: "KLP_A_05", doc_id: "KLP_A_05", nomor_absen: "05", nama_lengkap: "Evander Kalle Alvaro", kelompok: "KELOMPOK A" },
  { id: "KLP_A_06", doc_id: "KLP_A_06", nomor_absen: "06", nama_lengkap: "Giselle Emmanuela Claire Handaka", kelompok: "KELOMPOK A" },
  { id: "KLP_A_07", doc_id: "KLP_A_07", nomor_absen: "07", nama_lengkap: "Jarvis Cahaya Azzawan", kelompok: "KELOMPOK A" },
  { id: "KLP_A_08", doc_id: "KLP_A_08", nomor_absen: "08", nama_lengkap: "Jonathan Alvino Kuolin", kelompok: "KELOMPOK A" },
  { id: "KLP_A_09", doc_id: "KLP_A_09", nomor_absen: "09", nama_lengkap: "Jonathan Darren Sugiarto", kelompok: "KELOMPOK A" },
  { id: "KLP_A_10", doc_id: "KLP_A_10", nomor_absen: "10", nama_lengkap: "Jose Othniel Sutanto", kelompok: "KELOMPOK A" },
  { id: "KLP_A_11", doc_id: "KLP_A_11", nomor_absen: "11", nama_lengkap: "Joshua Christofer Valeriu Hartanto", kelompok: "KELOMPOK A" },
  { id: "KLP_A_12", doc_id: "KLP_A_12", nomor_absen: "12", nama_lengkap: "Karunia Putri", kelompok: "KELOMPOK A" },
  { id: "KLP_A_13", doc_id: "KLP_A_13", nomor_absen: "13", nama_lengkap: "Kezia Lawrence Gunawan", kelompok: "KELOMPOK A" },
  { id: "KLP_A_14", doc_id: "KLP_A_14", nomor_absen: "14", nama_lengkap: "Kimberlly Santoso", kelompok: "KELOMPOK A" },
  { id: "KLP_A_15", doc_id: "KLP_A_15", nomor_absen: "15", nama_lengkap: "Kiraniya Jordyn Kuriake", kelompok: "KELOMPOK A" },
  { id: "KLP_A_16", doc_id: "KLP_A_16", nomor_absen: "16", nama_lengkap: "Lachtara Easterani Sembiring", kelompok: "KELOMPOK A" },
  { id: "KLP_A_17", doc_id: "KLP_A_17", nomor_absen: "17", nama_lengkap: "Maria Fontanella Yovi Phoebe C.", kelompok: "KELOMPOK A" },
  { id: "KLP_A_18", doc_id: "KLP_A_18", nomor_absen: "18", nama_lengkap: "Nadya Kinanti Rantelimbong", kelompok: "KELOMPOK A" },
  { id: "KLP_A_19", doc_id: "KLP_A_19", nomor_absen: "19", nama_lengkap: "Naomi Jesselyn Andretti", kelompok: "KELOMPOK A" },
  { id: "KLP_A_20", doc_id: "KLP_A_20", nomor_absen: "20", nama_lengkap: "Nathanael Indrawan", kelompok: "KELOMPOK A" },
  { id: "KLP_A_21", doc_id: "KLP_A_21", nomor_absen: "21", nama_lengkap: "Nathania Deven Kurniawan", kelompok: "KELOMPOK A" },
  { id: "KLP_A_22", doc_id: "KLP_A_22", nomor_absen: "22", nama_lengkap: "Olimfia Fransine Wiensdy", kelompok: "KELOMPOK A" },
  { id: "KLP_A_23", doc_id: "KLP_A_23", nomor_absen: "23", nama_lengkap: "Radithya Vito Dewantoro", kelompok: "KELOMPOK A" },
  { id: "KLP_A_24", doc_id: "KLP_A_24", nomor_absen: "24", nama_lengkap: "Ron Kaylla Jeslyn", kelompok: "KELOMPOK A" },
  { id: "KLP_A_25", doc_id: "KLP_A_25", nomor_absen: "25", nama_lengkap: "Velisia Angela", kelompok: "KELOMPOK A" },
  { id: "KLP_A_26", doc_id: "KLP_A_26", nomor_absen: "26", nama_lengkap: "Vidia Larashati Ardya Prameswari", kelompok: "KELOMPOK A" },
  { id: "KLP_A_27", doc_id: "KLP_A_27", nomor_absen: "27", nama_lengkap: "Vince Vallent Christie Saputro", kelompok: "KELOMPOK A" },
  { id: "KLP_A_28", doc_id: "KLP_A_28", nomor_absen: "28", nama_lengkap: "Vincentius Vymanasthra Rygiera", kelompok: "KELOMPOK A" },
  { id: "KLP_A_29", doc_id: "KLP_A_29", nomor_absen: "29", nama_lengkap: "Widjayanti Andayananing Kusumo H.", kelompok: "KELOMPOK A" },
  { id: "KLP_A_30", doc_id: "KLP_A_30", nomor_absen: "30", nama_lengkap: "Xian Ratna Gemilang", kelompok: "KELOMPOK A" },
  { id: "KLP_A_31", doc_id: "KLP_A_31", nomor_absen: "31", nama_lengkap: "Zheysa Martharich Zellia Putri", kelompok: "KELOMPOK A" },
  

  // ==================== KELOMPOK B (32 Siswa) ====================
  { id: "KLP_B_01", doc_id: "KLP_B_01", nomor_absen: "01", nama_lengkap: "Adrianus Radhitya Pramata Rahagi", kelompok: "KELOMPOK B" },
  { id: "KLP_B_02", doc_id: "KLP_B_02", nomor_absen: "02", nama_lengkap: "Aileen Bellvania Hadisuryo", kelompok: "KELOMPOK B" },
  { id: "KLP_B_03", doc_id: "KLP_B_03", nomor_absen: "03", nama_lengkap: "Aloysius Banyu Bening", kelompok: "KELOMPOK B" },
  { id: "KLP_B_04", doc_id: "KLP_B_04", nomor_absen: "04", nama_lengkap: "Amrita Kalyani Fauzi", kelompok: "KELOMPOK B" },
  { id: "KLP_B_05", doc_id: "KLP_B_05", nomor_absen: "05", nama_lengkap: "Bryan Elbert Andrian", kelompok: "KELOMPOK B" },
  { id: "KLP_B_06", doc_id: "KLP_B_06", nomor_absen: "06", nama_lengkap: "Cirrillo Dave Timothy Sinclair", kelompok: "KELOMPOK B" },
  { id: "KLP_B_07", doc_id: "KLP_B_07", nomor_absen: "07", nama_lengkap: "Fabianus Juan Haryanto", kelompok: "KELOMPOK B" },
  { id: "KLP_B_08", doc_id: "KLP_B_08", nomor_absen: "08", nama_lengkap: "Farrel Diovan Susanto", kelompok: "KELOMPOK B" },
  { id: "KLP_B_09", doc_id: "KLP_B_09", nomor_absen: "09", nama_lengkap: "Felicia Josephine Arbian Putricia", kelompok: "KELOMPOK B" },
  { id: "KLP_B_10", doc_id: "KLP_B_10", nomor_absen: "10", nama_lengkap: "Felicia Nathania", kelompok: "KELOMPOK B" },
  { id: "KLP_B_11", doc_id: "KLP_B_11", nomor_absen: "11", nama_lengkap: "Filipus Praiseloi Hineni", kelompok: "KELOMPOK B" },
  { id: "KLP_B_12", doc_id: "KLP_B_12", nomor_absen: "12", nama_lengkap: "Fiony Gracia Setiawan", kelompok: "KELOMPOK B" },
  { id: "KLP_B_13", doc_id: "KLP_B_13", nomor_absen: "13", nama_lengkap: "Gevariel Alvinlio Adyatama Nugraha", kelompok: "KELOMPOK B" },
  { id: "KLP_B_14", doc_id: "KLP_B_14", nomor_absen: "14", nama_lengkap: "Grace Tania Biantoro", kelompok: "KELOMPOK B" },
  { id: "KLP_B_15", doc_id: "KLP_B_15", nomor_absen: "15", nama_lengkap: "Gustin Javiers Tjokrohandoko", kelompok: "KELOMPOK B" },
  { id: "KLP_B_16", doc_id: "KLP_B_16", nomor_absen: "16", nama_lengkap: "Jeremy Miracle Hendy Putra", kelompok: "KELOMPOK B" },
  { id: "KLP_B_17", doc_id: "KLP_B_17", nomor_absen: "17", nama_lengkap: "Jimmylo Nathanael Wijaya", kelompok: "KELOMPOK B" },
  { id: "KLP_B_18", doc_id: "KLP_B_18", nomor_absen: "18", nama_lengkap: "Joevanca Monic Santosa", kelompok: "KELOMPOK B" },
  { id: "KLP_B_19", doc_id: "KLP_B_19", nomor_absen: "19", nama_lengkap: "Jovan Christopher Adji", kelompok: "KELOMPOK B" },
  { id: "KLP_B_20", doc_id: "KLP_B_20", nomor_absen: "20", nama_lengkap: "Lucia Trifosa", kelompok: "KELOMPOK B" },
  { id: "KLP_B_21", doc_id: "KLP_B_21", nomor_absen: "21", nama_lengkap: "Mikael Flavio Bagus Puja Raharja", kelompok: "KELOMPOK B" },
  { id: "KLP_B_22", doc_id: "KLP_B_22", nomor_absen: "22", nama_lengkap: "Nathania Sherren Rahardja", kelompok: "KELOMPOK B" },
  { id: "KLP_B_23", doc_id: "KLP_B_23", nomor_absen: "23", nama_lengkap: "Owen Given Kurnia Sutrisna", kelompok: "KELOMPOK B" },
  { id: "KLP_B_24", doc_id: "KLP_B_24", nomor_absen: "24", nama_lengkap: "Patricia Nicole Setiawan", kelompok: "KELOMPOK B" },
  { id: "KLP_B_25", doc_id: "KLP_B_25", nomor_absen: "25", nama_lengkap: "Praise Adonai Ari Nugroho", kelompok: "KELOMPOK B" },
  { id: "KLP_B_26", doc_id: "KLP_B_26", nomor_absen: "26", nama_lengkap: "Rafael Artorius Pradipta", kelompok: "KELOMPOK B" },
  { id: "KLP_B_27", doc_id: "KLP_B_27", nomor_absen: "27", nama_lengkap: "Rafael Tondi Yoshua Putra", kelompok: "KELOMPOK B" },
  { id: "KLP_B_28", doc_id: "KLP_B_28", nomor_absen: "28", nama_lengkap: "Royce Wesley Chandra", kelompok: "KELOMPOK B" },
  { id: "KLP_B_29", doc_id: "KLP_B_29", nomor_absen: "29", nama_lengkap: "Samuel Evan Jatmiko", kelompok: "KELOMPOK B" },
  { id: "KLP_B_30", doc_id: "KLP_B_30", nomor_absen: "30", nama_lengkap: "Stephanie Adiska Karunia", kelompok: "KELOMPOK B" },
  { id: "KLP_B_31", doc_id: "KLP_B_31", nomor_absen: "31", nama_lengkap: "Stevanus Alvino Diandra Putra", kelompok: "KELOMPOK B" },
  { id: "KLP_B_32", doc_id: "KLP_B_32", nomor_absen: "32", nama_lengkap: "Veronica Kimberly Suyanto", kelompok: "KELOMPOK B" },
  // ==================== KELOMPOK C (31 Siswa) ====================
  { id: "KLP_C_01", doc_id: "KLP_C_01", nomor_absen: "01", nama_lengkap: "Akio Keitaro", kelompok: "KELOMPOK C" },
  { id: "KLP_C_02", doc_id: "KLP_C_02", nomor_absen: "02", nama_lengkap: "Anathasya Kimberly Haditama", kelompok: "KELOMPOK C" },
  { id: "KLP_C_03", doc_id: "KLP_C_03", nomor_absen: "03", nama_lengkap: "Angel Putri Raharja", kelompok: "KELOMPOK C" },
  { id: "KLP_C_04", doc_id: "KLP_C_04", nomor_absen: "04", nama_lengkap: "Angelina Nadine Hartanto", kelompok: "KELOMPOK C" },
  { id: "KLP_C_05", doc_id: "KLP_C_05", nomor_absen: "05", nama_lengkap: "Aquino Kay Dei Holman", kelompok: "KELOMPOK C" },
  { id: "KLP_C_06", doc_id: "KLP_C_06", nomor_absen: "06", nama_lengkap: "Benaya Herdi Wantoro", kelompok: "KELOMPOK C" },
  { id: "KLP_C_07", doc_id: "KLP_C_07", nomor_absen: "07", nama_lengkap: "Benecio Calvin Haluvri", kelompok: "KELOMPOK C" },
  { id: "KLP_C_08", doc_id: "KLP_C_08", nomor_absen: "08", nama_lengkap: "Calista Aurora Wibowo", kelompok: "KELOMPOK C" },
  { id: "KLP_C_09", doc_id: "KLP_C_09", nomor_absen: "09", nama_lengkap: "Carissa Nathaniela", kelompok: "KELOMPOK C" },
  { id: "KLP_C_10", doc_id: "KLP_C_10", nomor_absen: "10", nama_lengkap: "Chelsy Priscilla Budhianto", kelompok: "KELOMPOK C" },
  { id: "KLP_C_11", doc_id: "KLP_C_11", nomor_absen: "11", nama_lengkap: "Delfina Roanna Joyan Gunawan", kelompok: "KELOMPOK C" },
  { id: "KLP_C_12", doc_id: "KLP_C_12", nomor_absen: "12", nama_lengkap: "Edwardo Jonathan Anggoro", kelompok: "KELOMPOK C" },
  { id: "KLP_C_13", doc_id: "KLP_C_13", nomor_absen: "13", nama_lengkap: "Fabian Archie Hartono", kelompok: "KELOMPOK C" },
  { id: "KLP_C_14", doc_id: "KLP_C_14", nomor_absen: "14", nama_lengkap: "Florentina Ganya Clarinta Kurnia P.", kelompok: "KELOMPOK C" },
  { id: "KLP_C_15", doc_id: "KLP_C_15", nomor_absen: "15", nama_lengkap: "Jacquelline Nayaka Nirwasita", kelompok: "KELOMPOK C" },
  { id: "KLP_C_16", doc_id: "KLP_C_16", nomor_absen: "16", nama_lengkap: "Jocelyn Jefta Darmodjo", kelompok: "KELOMPOK C" },
  { id: "KLP_C_17", doc_id: "KLP_C_17", nomor_absen: "17", nama_lengkap: "Joshua Musa Jason Nugroho", kelompok: "KELOMPOK C" },
  { id: "KLP_C_18", doc_id: "KLP_C_18", nomor_absen: "18", nama_lengkap: "Maleakhi Agra Raditya", kelompok: "KELOMPOK C" },
  { id: "KLP_C_19", doc_id: "KLP_C_19", nomor_absen: "19", nama_lengkap: "Maria Amelia Supangat", kelompok: "KELOMPOK C" },
  { id: "KLP_C_20", doc_id: "KLP_C_20", nomor_absen: "20", nama_lengkap: "Maria Andini Lintang Putri", kelompok: "KELOMPOK C" },
  { id: "KLP_C_21", doc_id: "KLP_C_21", nomor_absen: "21", nama_lengkap: "Maria Avelina Wicaksono", kelompok: "KELOMPOK C" },
  { id: "KLP_C_22", doc_id: "KLP_C_22", nomor_absen: "22", nama_lengkap: "Maria Calista Yoiva", kelompok: "KELOMPOK C" },
  { id: "KLP_C_23", doc_id: "KLP_C_23", nomor_absen: "23", nama_lengkap: "Melvin Fey Osman", kelompok: "KELOMPOK C" },
  { id: "KLP_C_24", doc_id: "KLP_C_24", nomor_absen: "24", nama_lengkap: "Mutiara Anggita Putri Santoso", kelompok: "KELOMPOK C" },
  { id: "KLP_C_25", doc_id: "KLP_C_25", nomor_absen: "25", nama_lengkap: "Nathanael Timothy Adiwijaya", kelompok: "KELOMPOK C" },
  { id: "KLP_C_26", doc_id: "KLP_C_26", nomor_absen: "26", nama_lengkap: "Rafael Adelio Saputra", kelompok: "KELOMPOK C" },
  { id: "KLP_C_27", doc_id: "KLP_C_27", nomor_absen: "27", nama_lengkap: "Rafael Raditya Saputra", kelompok: "KELOMPOK C" },
  { id: "KLP_C_28", doc_id: "KLP_C_28", nomor_absen: "28", nama_lengkap: "Severin Viona Setiawan", kelompok: "KELOMPOK C" },
  { id: "KLP_C_29", doc_id: "KLP_C_29", nomor_absen: "29", nama_lengkap: "Vivian Natalie", kelompok: "KELOMPOK C" },
  { id: "KLP_C_30", doc_id: "KLP_C_30", nomor_absen: "30", nama_lengkap: "William Reynard Arthur Whyett", kelompok: "KELOMPOK C" },
  { id: "KLP_C_31", doc_id: "KLP_C_31", nomor_absen: "31", nama_lengkap: "Yuji Timothy Sinaga", kelompok: "KELOMPOK C" },

  // ==================== KELOMPOK D (31 Siswa) ====================
  { id: "KLP_D_01", doc_id: "KLP_D_01", nomor_absen: "01", nama_lengkap: "Adhitya Sugiarto", kelompok: "KELOMPOK D" },
  { id: "KLP_D_02", doc_id: "KLP_D_02", nomor_absen: "02", nama_lengkap: "Aisya Shima Tan", kelompok: "KELOMPOK D" },
  { id: "KLP_D_03", doc_id: "KLP_D_03", nomor_absen: "03", nama_lengkap: "Alitheia Chatarina", kelompok: "KELOMPOK D" },
  { id: "KLP_D_04", doc_id: "KLP_D_04", nomor_absen: "04", nama_lengkap: "Anna Maria Shorella Ananingtyas N.", kelompok: "KELOMPOK D" },
  { id: "KLP_D_05", doc_id: "KLP_D_05", nomor_absen: "05", nama_lengkap: "Ayleen Putri Nugroho", kelompok: "KELOMPOK D" },
  { id: "KLP_D_06", doc_id: "KLP_D_06", nomor_absen: "06", nama_lengkap: "Celia Timothy", kelompok: "KELOMPOK D" },
  { id: "KLP_D_07", doc_id: "KLP_D_07", nomor_absen: "07", nama_lengkap: "Christophorus Noel Ajinugroho", kelompok: "KELOMPOK D" },
  { id: "KLP_D_08", doc_id: "KLP_D_08", nomor_absen: "08", nama_lengkap: "David Dimasreja Praptadi", kelompok: "KELOMPOK D" },
  { id: "KLP_D_09", doc_id: "KLP_D_09", nomor_absen: "09", nama_lengkap: "Denise Jessica Arthur", kelompok: "KELOMPOK D" },
  { id: "KLP_D_10", doc_id: "KLP_D_10", nomor_absen: "10", nama_lengkap: "Dominique Hendranata Ts", kelompok: "KELOMPOK D" },
  { id: "KLP_D_11", doc_id: "KLP_D_11", nomor_absen: "11", nama_lengkap: "Felicia Kurniawan", kelompok: "KELOMPOK D" },
  { id: "KLP_D_12", doc_id: "KLP_D_12", nomor_absen: "12", nama_lengkap: "Fellicia Anggun Nirwasita", kelompok: "KELOMPOK D" },
  { id: "KLP_D_13", doc_id: "KLP_D_13", nomor_absen: "13", nama_lengkap: "Geovanni Hosea Rhianditya", kelompok: "KELOMPOK D" },
  { id: "KLP_D_14", doc_id: "KLP_D_14", nomor_absen: "14", nama_lengkap: "Gladys Zavira Ariansyah", kelompok: "KELOMPOK D" },
  { id: "KLP_D_15", doc_id: "KLP_D_15", nomor_absen: "15", nama_lengkap: "Gregoria Keisha Calysta", kelompok: "KELOMPOK D" },
  { id: "KLP_D_16", doc_id: "KLP_D_16", nomor_absen: "16", nama_lengkap: "Joycelyn Oktavia Susanto", kelompok: "KELOMPOK D" },
  { id: "KLP_D_17", doc_id: "KLP_D_17", nomor_absen: "17", nama_lengkap: "Keyza Louis Pratama", kelompok: "KELOMPOK D" },
  { id: "KLP_D_18", doc_id: "KLP_D_18", nomor_absen: "18", nama_lengkap: "Laurentia Fellice Iswanto", kelompok: "KELOMPOK D" },
  { id: "KLP_D_19", doc_id: "KLP_D_19", nomor_absen: "19", nama_lengkap: "Leticia Juanetta Prasetio", kelompok: "KELOMPOK D" },
  { id: "KLP_D_20", doc_id: "KLP_D_20", nomor_absen: "20", nama_lengkap: "Loveina Gabriela Pratomo", kelompok: "KELOMPOK D" },
  { id: "KLP_D_21", doc_id: "KLP_D_21", nomor_absen: "21", nama_lengkap: "Michael Gennaro Milagro", kelompok: "KELOMPOK D" },
  { id: "KLP_D_22", doc_id: "KLP_D_22", nomor_absen: "22", nama_lengkap: "Natalia Puspita Dewi", kelompok: "KELOMPOK D" },
  { id: "KLP_D_23", doc_id: "KLP_D_23", nomor_absen: "23", nama_lengkap: "Samuel Pranoto Singgih", kelompok: "KELOMPOK D" },
  { id: "KLP_D_24", doc_id: "KLP_D_24", nomor_absen: "24", nama_lengkap: "Theresia Deianira Calista Nareswari", kelompok: "KELOMPOK D" },
  { id: "KLP_D_25", doc_id: "KLP_D_25", nomor_absen: "25", nama_lengkap: "Valentino Marcel Setiawan", kelompok: "KELOMPOK D" },
  { id: "KLP_D_26", doc_id: "KLP_D_26", nomor_absen: "26", nama_lengkap: "Valeria Maurenzi Audryna Christie", kelompok: "KELOMPOK D" },
  { id: "KLP_D_27", doc_id: "KLP_D_27", nomor_absen: "27", nama_lengkap: "Vanessa Aurelia Aritonang", kelompok: "KELOMPOK D" },
  { id: "KLP_D_28", doc_id: "KLP_D_28", nomor_absen: "28", nama_lengkap: "Vincensius Andra Yudhistira", kelompok: "KELOMPOK D" },
  { id: "KLP_D_29", doc_id: "KLP_D_29", nomor_absen: "29", nama_lengkap: "William Riyanto", kelompok: "KELOMPOK D" },
  { id: "KLP_D_30", doc_id: "KLP_D_30", nomor_absen: "30", nama_lengkap: "Yehezkiel Vincent Hartono", kelompok: "KELOMPOK D" },
  { id: "KLP_D_31", doc_id: "KLP_D_31", nomor_absen: "31", nama_lengkap: "Yohanes Aditya Wijanarko", kelompok: "KELOMPOK D" },

  // ==================== KELOMPOK E (31 Siswa) ====================
  { id: "KLP_E_01", doc_id: "KLP_E_01", nomor_absen: "01", nama_lengkap: "Abimanyu Silloam Kayana", kelompok: "KELOMPOK E" },
  { id: "KLP_E_02", doc_id: "KLP_E_02", nomor_absen: "02", nama_lengkap: "Adelaide Jasmine Allana Uthomo", kelompok: "KELOMPOK E" },
  { id: "KLP_E_03", doc_id: "KLP_E_03", nomor_absen: "03", nama_lengkap: "Beatrice Candy Santoso", kelompok: "KELOMPOK E" },
  { id: "KLP_E_04", doc_id: "KLP_E_04", nomor_absen: "04", nama_lengkap: "Cathleen Daniela Tjahjadi Widjanarko", kelompok: "KELOMPOK E" },
  { id: "KLP_E_05", doc_id: "KLP_E_05", nomor_absen: "05", nama_lengkap: "Claresta Vianey Lamintha", kelompok: "KELOMPOK E" },
  { id: "KLP_E_06", doc_id: "KLP_E_06", nomor_absen: "06", nama_lengkap: "Delano Nicklaus Kurniawan", kelompok: "KELOMPOK E" },
  { id: "KLP_E_07", doc_id: "KLP_E_07", nomor_absen: "07", nama_lengkap: "Evangelina Delmara Tutuarima", kelompok: "KELOMPOK E" },
  { id: "KLP_E_08", doc_id: "KLP_E_08", nomor_absen: "08", nama_lengkap: "Felicia Ivana Haryanto", kelompok: "KELOMPOK E" },
  { id: "KLP_E_09", doc_id: "KLP_E_09", nomor_absen: "09", nama_lengkap: "Fiorenza Levana Santoso", kelompok: "KELOMPOK E" },
  { id: "KLP_E_10", doc_id: "KLP_E_10", nomor_absen: "10", nama_lengkap: "Gabriel Cleandro Anjasa Prassana", kelompok: "KELOMPOK E" },
  { id: "KLP_E_11", doc_id: "KLP_E_11", nomor_absen: "11", nama_lengkap: "Gabriella Jessica Hu", kelompok: "KELOMPOK E" },
  { id: "KLP_E_12", doc_id: "KLP_E_12", nomor_absen: "12", nama_lengkap: "Gisella Evangeline Raharjo", kelompok: "KELOMPOK E" },
  { id: "KLP_E_13", doc_id: "KLP_E_13", nomor_absen: "13", nama_lengkap: "Ignatia Jasmine Wardhana", kelompok: "KELOMPOK E" },
  { id: "KLP_E_14", doc_id: "KLP_E_14", nomor_absen: "14", nama_lengkap: "Jessica Kyrana Cahyaningtyas", kelompok: "KELOMPOK E" },
  { id: "KLP_E_15", doc_id: "KLP_E_15", nomor_absen: "15", nama_lengkap: "Joseph Jevaro Garudatama Mekranto", kelompok: "KELOMPOK E" },
  { id: "KLP_E_16", doc_id: "KLP_E_16", nomor_absen: "16", nama_lengkap: "Jovanka Abigail Djodana", kelompok: "KELOMPOK E" },
  { id: "KLP_E_17", doc_id: "KLP_E_17", nomor_absen: "17", nama_lengkap: "Karelyn Letichia Kartono", kelompok: "KELOMPOK E" },
  { id: "KLP_E_18", doc_id: "KLP_E_18", nomor_absen: "18", nama_lengkap: "Keiko Quinnchiera Purnomo", kelompok: "KELOMPOK E" },
  { id: "KLP_E_19", doc_id: "KLP_E_19", nomor_absen: "19", nama_lengkap: "Kent Aryo Alexander Lim", kelompok: "KELOMPOK E" },
  { id: "KLP_E_20", doc_id: "KLP_E_20", nomor_absen: "20", nama_lengkap: "Looky Jeiy Lion", kelompok: "KELOMPOK E" },
  { id: "KLP_E_21", doc_id: "KLP_E_21", nomor_absen: "21", nama_lengkap: "Maria Alycia Handoko", kelompok: "KELOMPOK E" },
  { id: "KLP_E_22", doc_id: "KLP_E_22", nomor_absen: "22", nama_lengkap: "Nathanael Calvin Wibowo", kelompok: "KELOMPOK E" },
  { id: "KLP_E_23", doc_id: "KLP_E_23", nomor_absen: "23", nama_lengkap: "Owen Julio Setiawan", kelompok: "KELOMPOK E" },
  { id: "KLP_E_24", doc_id: "KLP_E_24", nomor_absen: "24", nama_lengkap: "R.Cattleya Alexa Sandra", kelompok: "KELOMPOK E" },
  { id: "KLP_E_25", doc_id: "KLP_E_25", nomor_absen: "25", nama_lengkap: "Rafael Wahyu Saputra", kelompok: "KELOMPOK E" },
  { id: "KLP_E_26", doc_id: "KLP_E_26", nomor_absen: "26", nama_lengkap: "Rafaella Paskalin Putri Wicaksono", kelompok: "KELOMPOK E" },
  { id: "KLP_E_27", doc_id: "KLP_E_27", nomor_absen: "27", nama_lengkap: "Stanislaus Raditya Anantya Jati", kelompok: "KELOMPOK E" },
  { id: "KLP_E_28", doc_id: "KLP_E_28", nomor_absen: "28", nama_lengkap: "Tan Callista Joyce Bastari", kelompok: "KELOMPOK E" },
  { id: "KLP_E_29", doc_id: "KLP_E_29", nomor_absen: "29", nama_lengkap: "Tan, Patricia Lola Ellen Setiawan", kelompok: "KELOMPOK E" },
  { id: "KLP_E_30", doc_id: "KLP_E_30", nomor_absen: "30", nama_lengkap: "Vincentius Maria Damian", kelompok: "KELOMPOK E" },
  { id: "KLP_E_31", doc_id: "KLP_E_31", nomor_absen: "31", nama_lengkap: "Vincentius Vidian Aditama", kelompok: "KELOMPOK E" },

  // ==================== KELOMPOK F (31 Siswa) ====================
  { id: "KLP_F_01", doc_id: "KLP_F_01", nomor_absen: "01", nama_lengkap: "Adelia Nathalie Prasasti", kelompok: "KELOMPOK F" },
  { id: "KLP_F_02", doc_id: "KLP_F_02", nomor_absen: "02", nama_lengkap: "Aishwarya Chandeny Deevnita A.K", kelompok: "KELOMPOK F" },
  { id: "KLP_F_03", doc_id: "KLP_F_03", nomor_absen: "03", nama_lengkap: "Angela Natasha", kelompok: "KELOMPOK F" },
  { id: "KLP_F_04", doc_id: "KLP_F_04", nomor_absen: "04", nama_lengkap: "Aurelia Michele Purnomo", kelompok: "KELOMPOK F" },
  { id: "KLP_F_05", doc_id: "KLP_F_05", nomor_absen: "05", nama_lengkap: "Cecilia Irene Setiawan", kelompok: "KELOMPOK F" },
  { id: "KLP_F_06", doc_id: "KLP_F_06", nomor_absen: "06", nama_lengkap: "Chaterine Letitia Chan", kelompok: "KELOMPOK F" },
  { id: "KLP_F_07", doc_id: "KLP_F_07", nomor_absen: "07", nama_lengkap: "Christopher Ganendra", kelompok: "KELOMPOK F" },
  { id: "KLP_F_08", doc_id: "KLP_F_08", nomor_absen: "08", nama_lengkap: "Christopher Satria Wicaksana Nugraha", kelompok: "KELOMPOK F" },
  { id: "KLP_F_09", doc_id: "KLP_F_09", nomor_absen: "09", nama_lengkap: "Christopher Timothy Irawan", kelompok: "KELOMPOK F" },
  { id: "KLP_F_10", doc_id: "KLP_F_10", nomor_absen: "10", nama_lengkap: "Claire Amabelle Ong", kelompok: "KELOMPOK F" },
  { id: "KLP_F_11", doc_id: "KLP_F_11", nomor_absen: "11", nama_lengkap: "Constantine Aurelia Prihandoko", kelompok: "KELOMPOK F" },
  { id: "KLP_F_12", doc_id: "KLP_F_12", nomor_absen: "12", nama_lengkap: "Dominique Leticia", kelompok: "KELOMPOK F" },
  { id: "KLP_F_13", doc_id: "KLP_F_13", nomor_absen: "13", nama_lengkap: "Felicia Jesslyn Nata", kelompok: "KELOMPOK F" },
  { id: "KLP_F_14", doc_id: "KLP_F_14", nomor_absen: "14", nama_lengkap: "Felixco Anthonick Pranata", kelompok: "KELOMPOK F" },
  { id: "KLP_F_15", doc_id: "KLP_F_15", nomor_absen: "15", nama_lengkap: "Fiorenza Abigail Susanto", kelompok: "KELOMPOK F" },
  { id: "KLP_F_16", doc_id: "KLP_F_16", nomor_absen: "16", nama_lengkap: "Gregorios Thaumaturgos Chandra", kelompok: "KELOMPOK F" },
  { id: "KLP_F_17", doc_id: "KLP_F_17", nomor_absen: "17", nama_lengkap: "Gregorius Richard Jeremy Jap", kelompok: "KELOMPOK F" },
  { id: "KLP_F_18", doc_id: "KLP_F_18", nomor_absen: "18", nama_lengkap: "Immanuel Yusuf Tj Setiawan", kelompok: "KELOMPOK F" },
  { id: "KLP_F_19", doc_id: "KLP_F_19", nomor_absen: "19", nama_lengkap: "Irene Tiurlyn Darmawan", kelompok: "KELOMPOK F" },
  { id: "KLP_F_20", doc_id: "KLP_F_20", nomor_absen: "20", nama_lengkap: "Jessica Aurelia Prasetyo", kelompok: "KELOMPOK F" },
  { id: "KLP_F_21", doc_id: "KLP_F_21", nomor_absen: "21", nama_lengkap: "Justinus Adrian Pratama", kelompok: "KELOMPOK F" },
  { id: "KLP_F_22", doc_id: "KLP_F_22", nomor_absen: "22", nama_lengkap: "Lettycia Angie Nugroho", kelompok: "KELOMPOK F" },
  { id: "KLP_F_23", doc_id: "KLP_F_23", nomor_absen: "23", nama_lengkap: "Liam Wesley Sena", kelompok: "KELOMPOK F" },
  { id: "KLP_F_24", doc_id: "KLP_F_24", nomor_absen: "24", nama_lengkap: "Maximos Sindhuatmadja", kelompok: "KELOMPOK F" },
  { id: "KLP_F_25", doc_id: "KLP_F_25", nomor_absen: "25", nama_lengkap: "Michelle Alberta Nugroho", kelompok: "KELOMPOK F" },
  { id: "KLP_F_26", doc_id: "KLP_F_26", nomor_absen: "26", nama_lengkap: "Naomi Justicia Kamka", kelompok: "KELOMPOK F" },
  { id: "KLP_F_27", doc_id: "KLP_F_27", nomor_absen: "27", nama_lengkap: "Nice Valerie Padmaliem", kelompok: "KELOMPOK F" },
  { id: "KLP_F_28", doc_id: "KLP_F_28", nomor_absen: "28", nama_lengkap: "Skolastika Surya Nayra Prashinta", kelompok: "KELOMPOK F" },
  { id: "KLP_F_29", doc_id: "KLP_F_29", nomor_absen: "29", nama_lengkap: "Timothy Davin Susanto", kelompok: "KELOMPOK F" },
  { id: "KLP_F_30", doc_id: "KLP_F_30", nomor_absen: "30", nama_lengkap: "Timothy Morgan Setiawan", kelompok: "KELOMPOK F" },
  { id: "KLP_F_31", doc_id: "KLP_F_31", nomor_absen: "31", nama_lengkap: "Veronica Sandra Kirana Ekaristi", kelompok: "KELOMPOK F" },

  // ==================== KELOMPOK G (31 Siswa) ====================
  { id: "KLP_G_01", doc_id: "KLP_G_01", nomor_absen: "01", nama_lengkap: "Alethea Efra Gracia", kelompok: "KELOMPOK G" },
  { id: "KLP_G_02", doc_id: "KLP_G_02", nomor_absen: "02", nama_lengkap: "Amadea Greta Adiputri", kelompok: "KELOMPOK G" },
  { id: "KLP_G_03", doc_id: "KLP_G_03", nomor_absen: "03", nama_lengkap: "Andrew Yanuwihardjo", kelompok: "KELOMPOK G" },
  { id: "KLP_G_04", doc_id: "KLP_G_04", nomor_absen: "04", nama_lengkap: "Aurellia Gracia Hendricco", kelompok: "KELOMPOK G" },
  { id: "KLP_G_05", doc_id: "KLP_G_05", nomor_absen: "05", nama_lengkap: "Catherine Felicia William", kelompok: "KELOMPOK G" },
  { id: "KLP_G_06", doc_id: "KLP_G_06", nomor_absen: "06", nama_lengkap: "Daniella Christe Endhitya", kelompok: "KELOMPOK G" },
  { id: "KLP_G_07", doc_id: "KLP_G_07", nomor_absen: "07", nama_lengkap: "Daphne Miracle Efes Damim", kelompok: "KELOMPOK G" },
  { id: "KLP_G_08", doc_id: "KLP_G_08", nomor_absen: "08", nama_lengkap: "Dinda Shalom Putri Sakti", kelompok: "KELOMPOK G" },
  { id: "KLP_G_09", doc_id: "KLP_G_09", nomor_absen: "09", nama_lengkap: "Earlene Zanetha Harinda", kelompok: "KELOMPOK G" },
  { id: "KLP_G_10", doc_id: "KLP_G_10", nomor_absen: "10", nama_lengkap: "Eleonora Areta Haryanto", kelompok: "KELOMPOK G" },
  { id: "KLP_G_11", doc_id: "KLP_G_11", nomor_absen: "11", nama_lengkap: "Fiona Evelyn Supriyanto", kelompok: "KELOMPOK G" },
  { id: "KLP_G_12", doc_id: "KLP_G_12", nomor_absen: "12", nama_lengkap: "Fransiska Oriella Jasmine Prihutomo", kelompok: "KELOMPOK G" },
  { id: "KLP_G_13", doc_id: "KLP_G_13", nomor_absen: "13", nama_lengkap: "Gabrielle Happyness Silalahi", kelompok: "KELOMPOK G" },
  { id: "KLP_G_14", doc_id: "KLP_G_14", nomor_absen: "14", nama_lengkap: "Hansen Alexander Santoso", kelompok: "KELOMPOK G" },
  { id: "KLP_G_15", doc_id: "KLP_G_15", nomor_absen: "15", nama_lengkap: "Helena Theresia Wijaya", kelompok: "KELOMPOK G" },
  { id: "KLP_G_16", doc_id: "KLP_G_16", nomor_absen: "16", nama_lengkap: "Hugo Galih Pamenang", kelompok: "KELOMPOK G" },
  { id: "KLP_G_17", doc_id: "KLP_G_17", nomor_absen: "17", nama_lengkap: "Jayden Prince Adhisila", kelompok: "KELOMPOK G" },
  { id: "KLP_G_18", doc_id: "KLP_G_18", nomor_absen: "18", nama_lengkap: "Joscelyn Hens Claresta", kelompok: "KELOMPOK G" },
  { id: "KLP_G_19", doc_id: "KLP_G_19", nomor_absen: "19", nama_lengkap: "Joshua Immanuel Halim", kelompok: "KELOMPOK G" },
  { id: "KLP_G_20", doc_id: "KLP_G_20", nomor_absen: "20", nama_lengkap: "Joshua Kin Pandu Dharma", kelompok: "KELOMPOK G" },
  { id: "KLP_G_21", doc_id: "KLP_G_21", nomor_absen: "21", nama_lengkap: "Margareth Ester Batsyua Aharona", kelompok: "KELOMPOK G" },
  { id: "KLP_G_22", doc_id: "KLP_G_22", nomor_absen: "22", nama_lengkap: "Maria Elenoa Jaya Koseky", kelompok: "KELOMPOK G" },
  { id: "KLP_G_23", doc_id: "KLP_G_23", nomor_absen: "23", nama_lengkap: "Nathan Yoga Pramudito", kelompok: "KELOMPOK G" },
  { id: "KLP_G_24", doc_id: "KLP_G_24", nomor_absen: "24", nama_lengkap: "Rafael Veda Prasetio", kelompok: "KELOMPOK G" },
  { id: "KLP_G_25", doc_id: "KLP_G_25", nomor_absen: "25", nama_lengkap: "Raphael Kurnia Paramayoga Emiliano", kelompok: "KELOMPOK G" },
  { id: "KLP_G_26", doc_id: "KLP_G_26", nomor_absen: "26", nama_lengkap: "Ryuu Ethan Setyawan", kelompok: "KELOMPOK G" },
  { id: "KLP_G_27", doc_id: "KLP_G_27", nomor_absen: "27", nama_lengkap: "Sean Eugene Wijaya", kelompok: "KELOMPOK G" },
  { id: "KLP_G_28", doc_id: "KLP_G_28", nomor_absen: "28", nama_lengkap: "Stanislaus Cello Aditya Gunawan", kelompok: "KELOMPOK G" },
  { id: "KLP_G_29", doc_id: "KLP_G_29", nomor_absen: "29", nama_lengkap: "Steven Satria Wijaya", kelompok: "KELOMPOK G" },
  { id: "KLP_G_30", doc_id: "KLP_G_30", nomor_absen: "30", nama_lengkap: "Yohana Paulisa Suryanto", kelompok: "KELOMPOK G" },
  { id: "KLP_G_31", doc_id: "KLP_G_31", nomor_absen: "31", nama_lengkap: "Yohanes Bhagawanta", kelompok: "KELOMPOK G" },

  // ==================== KELOMPOK H (31 Siswa) ====================
  { id: "KLP_H_01", doc_id: "KLP_H_01", nomor_absen: "01", nama_lengkap: "Adelina Maheswari", kelompok: "KELOMPOK H" },
  { id: "KLP_H_02", doc_id: "KLP_H_02", nomor_absen: "02", nama_lengkap: "Alberth Jose Sidiprasetija", kelompok: "KELOMPOK H" },
  { id: "KLP_H_03", doc_id: "KLP_H_03", nomor_absen: "03", nama_lengkap: "Angela Christine Chandra", kelompok: "KELOMPOK H" },
  { id: "KLP_H_04", doc_id: "KLP_H_04", nomor_absen: "04", nama_lengkap: "Arkana Zelig Radinka Putra", kelompok: "KELOMPOK H" },
  { id: "KLP_H_05", doc_id: "KLP_H_05", nomor_absen: "05", nama_lengkap: "Avel Raynard Geiger", kelompok: "KELOMPOK H" },
  { id: "KLP_H_06", doc_id: "KLP_H_06", nomor_absen: "06", nama_lengkap: "Bonaventura Eugenio Raditya Mianglo", kelompok: "KELOMPOK H" },
  { id: "KLP_H_07", doc_id: "KLP_H_07", nomor_absen: "07", nama_lengkap: "Brigitta Christosia Pancoro", kelompok: "KELOMPOK H" },
  { id: "KLP_H_08", doc_id: "KLP_H_08", nomor_absen: "08", nama_lengkap: "Callysta Jesse Mathea", kelompok: "KELOMPOK H" },
  { id: "KLP_H_09", doc_id: "KLP_H_09", nomor_absen: "09", nama_lengkap: "Carol Angeline Apriyono", kelompok: "KELOMPOK H" },
  { id: "KLP_H_10", doc_id: "KLP_H_10", nomor_absen: "10", nama_lengkap: "Chevy Shane Pranatan", kelompok: "KELOMPOK H" },
  { id: "KLP_H_11", doc_id: "KLP_H_11", nomor_absen: "11", nama_lengkap: "Eka Setyo Ayu Dewanti", kelompok: "KELOMPOK H" },
  { id: "KLP_H_12", doc_id: "KLP_H_12", nomor_absen: "12", nama_lengkap: "Elisabeth Adinda Novenalia", kelompok: "KELOMPOK H" },
  { id: "KLP_H_13", doc_id: "KLP_H_13", nomor_absen: "13", nama_lengkap: "Gerald Chrysander Wijaya", kelompok: "KELOMPOK H" },
  { id: "KLP_H_14", doc_id: "KLP_H_14", nomor_absen: "14", nama_lengkap: "Ignatius Constantine Evan Setiawan", kelompok: "KELOMPOK H" },
  { id: "KLP_H_15", doc_id: "KLP_H_15", nomor_absen: "15", nama_lengkap: "Jessica Gracia Andita Liem", kelompok: "KELOMPOK H" },
  { id: "KLP_H_16", doc_id: "KLP_H_16", nomor_absen: "16", nama_lengkap: "Jillian Valencia Santoso", kelompok: "KELOMPOK H" },
  { id: "KLP_H_17", doc_id: "KLP_H_17", nomor_absen: "17", nama_lengkap: "Jonathan Delano", kelompok: "KELOMPOK H" },
  { id: "KLP_H_18", doc_id: "KLP_H_18", nomor_absen: "18", nama_lengkap: "Josep Gading Satritama", kelompok: "KELOMPOK H" },
  { id: "KLP_H_19", doc_id: "KLP_H_19", nomor_absen: "19", nama_lengkap: "Joseph Steven Aldorino", kelompok: "KELOMPOK H" },
  { id: "KLP_H_20", doc_id: "KLP_H_20", nomor_absen: "20", nama_lengkap: "Justin Evander Jayanto", kelompok: "KELOMPOK H" },
  { id: "KLP_H_21", doc_id: "KLP_H_21", nomor_absen: "21", nama_lengkap: "Justine Imanuel Wiyanto", kelompok: "KELOMPOK H" },
  { id: "KLP_H_22", doc_id: "KLP_H_22", nomor_absen: "22", nama_lengkap: "Kayleen Agatha Mulyadi", kelompok: "KELOMPOK H" },
  { id: "KLP_H_23", doc_id: "KLP_H_23", nomor_absen: "23", nama_lengkap: "Keanu Priesa Adhipratama", kelompok: "KELOMPOK H" },
  { id: "KLP_H_24", doc_id: "KLP_H_24", nomor_absen: "24", nama_lengkap: "Luke Deven Ardhani", kelompok: "KELOMPOK H" },
  { id: "KLP_H_25", doc_id: "KLP_H_25", nomor_absen: "25", nama_lengkap: "Marlisia", kelompok: "KELOMPOK H" },
  { id: "KLP_H_26", doc_id: "KLP_H_26", nomor_absen: "26", nama_lengkap: "Nicky Jason Lim", kelompok: "KELOMPOK H" },
  { id: "KLP_H_27", doc_id: "KLP_H_27", nomor_absen: "27", nama_lengkap: "Novenia Rasta Putri", kelompok: "KELOMPOK H" },
  { id: "KLP_H_28", doc_id: "KLP_H_28", nomor_absen: "28", nama_lengkap: "Pavitta Nathania Tan", kelompok: "KELOMPOK H" },
  { id: "KLP_H_29", doc_id: "KLP_H_29", nomor_absen: "29", nama_lengkap: "Quanika Liora Wijaya", kelompok: "KELOMPOK H" },
  { id: "KLP_H_30", doc_id: "KLP_H_30", nomor_absen: "30", nama_lengkap: "Regina Tertia Krista Aji", kelompok: "KELOMPOK H" },
  { id: "KLP_H_31", doc_id: "KLP_H_31", nomor_absen: "31", nama_lengkap: "Reinhart Parlindungan Banjarhor", kelompok: "KELOMPOK H" },

  // ==================== KELOMPOK I (31 Siswa) ====================
  { id: "KLP_I_01", doc_id: "KLP_I_01", nomor_absen: "01", nama_lengkap: "Aerylin Bellvania Sucittananda", kelompok: "KELOMPOK I" },
  { id: "KLP_I_02", doc_id: "KLP_I_02", nomor_absen: "02", nama_lengkap: "Bastiaans Jayden Nathaniel", kelompok: "KELOMPOK I" },
  { id: "KLP_I_03", doc_id: "KLP_I_03", nomor_absen: "03", nama_lengkap: "Brandon Vino Setiawan", kelompok: "KELOMPOK I" },
  { id: "KLP_I_04", doc_id: "KLP_I_04", nomor_absen: "04", nama_lengkap: "Chaitra Endra Nayottama", kelompok: "KELOMPOK I" },
  { id: "KLP_I_05", doc_id: "KLP_I_05", nomor_absen: "05", nama_lengkap: "Chaterine Winona Annabelle Saweho", kelompok: "KELOMPOK I" },
  { id: "KLP_I_06", doc_id: "KLP_I_06", nomor_absen: "06", nama_lengkap: "Chelsea Marasi Silonita Alexandra S.", kelompok: "KELOMPOK I" },
  { id: "KLP_I_07", doc_id: "KLP_I_07", nomor_absen: "07", nama_lengkap: "Christoval Vaughan Sumowidjojo", kelompok: "KELOMPOK I" },
  { id: "KLP_I_08", doc_id: "KLP_I_08", nomor_absen: "08", nama_lengkap: "Eleanor Naraya Prasetyo", kelompok: "KELOMPOK I" },
  { id: "KLP_I_09", doc_id: "KLP_I_09", nomor_absen: "09", nama_lengkap: "Eleonora Gwen Carissa Audrey H.", kelompok: "KELOMPOK I" },
  { id: "KLP_I_10", doc_id: "KLP_I_10", nomor_absen: "10", nama_lengkap: "Elisabeth Clarista Zoe Harytanto", kelompok: "KELOMPOK I" },
  { id: "KLP_I_11", doc_id: "KLP_I_11", nomor_absen: "11", nama_lengkap: "Fellicia Rara Ayu Anjali", kelompok: "KELOMPOK I" },
  { id: "KLP_I_12", doc_id: "KLP_I_12", nomor_absen: "12", nama_lengkap: "Gregorius Alvino Putra Nugroho", kelompok: "KELOMPOK I" },
  { id: "KLP_I_13", doc_id: "KLP_I_13", nomor_absen: "13", nama_lengkap: "Gwenn Nichola", kelompok: "KELOMPOK I" },
  { id: "KLP_I_14", doc_id: "KLP_I_14", nomor_absen: "14", nama_lengkap: "Hargian Alaric Prima Mulyawan", kelompok: "KELOMPOK I" },
  { id: "KLP_I_15", doc_id: "KLP_I_15", nomor_absen: "15", nama_lengkap: "Imanuela Clara Aysen Sigar", kelompok: "KELOMPOK I" },
  { id: "KLP_I_16", doc_id: "KLP_I_16", nomor_absen: "16", nama_lengkap: "Jazper Abivandya Suryanta", kelompok: "KELOMPOK I" },
  { id: "KLP_I_17", doc_id: "KLP_I_17", nomor_absen: "17", nama_lengkap: "Joshua Widagdo", kelompok: "KELOMPOK I" },
  { id: "KLP_I_18", doc_id: "KLP_I_18", nomor_absen: "18", nama_lengkap: "Maria Emanuelle Darlene Jeconia P.S.", kelompok: "KELOMPOK I" },
  { id: "KLP_I_19", doc_id: "KLP_I_19", nomor_absen: "19", nama_lengkap: "Michael Timothy Atmadja", kelompok: "KELOMPOK I" },
  { id: "KLP_I_20", doc_id: "KLP_I_20", nomor_absen: "20", nama_lengkap: "Michelle Emanuella Lumban Toruan", kelompok: "KELOMPOK I" },
  { id: "KLP_I_21", doc_id: "KLP_I_21", nomor_absen: "21", nama_lengkap: "Nathanael Lorenzo Criska Untoro", kelompok: "KELOMPOK I" },
  { id: "KLP_I_22", doc_id: "KLP_I_22", nomor_absen: "22", nama_lengkap: "Olivia Berlian Soegianto", kelompok: "KELOMPOK I" },
  { id: "KLP_I_23", doc_id: "KLP_I_23", nomor_absen: "23", nama_lengkap: "Orlando Noah Budi Cahyadi", kelompok: "KELOMPOK I" },
  { id: "KLP_I_24", doc_id: "KLP_I_24", nomor_absen: "24", nama_lengkap: "Osvaldo Gustave Abianko", kelompok: "KELOMPOK I" },
  { id: "KLP_I_25", doc_id: "KLP_I_25", nomor_absen: "25", nama_lengkap: "Rachel Ayudya Wibowo", kelompok: "KELOMPOK I" },
  { id: "KLP_I_26", doc_id: "KLP_I_26", nomor_absen: "26", nama_lengkap: "Rafaelle Giuseppe Najaoan", kelompok: "KELOMPOK I" },
  { id: "KLP_I_27", doc_id: "KLP_I_27", nomor_absen: "27", nama_lengkap: "Rafella Anna Diana Adi Sasongko", kelompok: "KELOMPOK I" },
  { id: "KLP_I_28", doc_id: "KLP_I_28", nomor_absen: "28", nama_lengkap: "Sacio Lionheart Purbowo", kelompok: "KELOMPOK I" },
  { id: "KLP_I_29", doc_id: "KLP_I_29", nomor_absen: "29", nama_lengkap: "Sherren Abriel Kurniandy", kelompok: "KELOMPOK I" },
  { id: "KLP_I_30", doc_id: "KLP_I_30", nomor_absen: "30", nama_lengkap: "Veronica Angela Wijaya", kelompok: "KELOMPOK I" },
  { id: "KLP_I_31", doc_id: "KLP_I_31", nomor_absen: "31", nama_lengkap: "Wicang Graning Aryoca", kelompok: "KELOMPOK I" },

  // ==================== KELOMPOK J (31 Siswa) ====================
  { id: "KLP_J_01", doc_id: "KLP_J_01", nomor_absen: "01", nama_lengkap: "Aimee Rochelle Dannica", kelompok: "KELOMPOK J" },
  { id: "KLP_J_02", doc_id: "KLP_J_02", nomor_absen: "02", nama_lengkap: "Anugerah Bintang Timur", kelompok: "KELOMPOK J" },
  { id: "KLP_J_03", doc_id: "KLP_J_03", nomor_absen: "03", nama_lengkap: "Brigitta Maurencia Johanna Gunarto", kelompok: "KELOMPOK J" },
  { id: "KLP_J_04", doc_id: "KLP_J_04", nomor_absen: "04", nama_lengkap: "Caroline Ivanna Seputro", kelompok: "KELOMPOK J" },
  { id: "KLP_J_05", doc_id: "KLP_J_05", nomor_absen: "05", nama_lengkap: "Christine Anna Mulia Jaya", kelompok: "KELOMPOK J" },
  { id: "KLP_J_06", doc_id: "KLP_J_06", nomor_absen: "06", nama_lengkap: "Darrell Yehuda Arbi Kristianto", kelompok: "KELOMPOK J" },
  { id: "KLP_J_07", doc_id: "KLP_J_07", nomor_absen: "07", nama_lengkap: "Darren Priyanto", kelompok: "KELOMPOK J" },
  { id: "KLP_J_08", doc_id: "KLP_J_08", nomor_absen: "08", nama_lengkap: "Devand Danu Krissatya", kelompok: "KELOMPOK J" },
  { id: "KLP_J_09", doc_id: "KLP_J_09", nomor_absen: "09", nama_lengkap: "Dylan Dimitri Jirou", kelompok: "KELOMPOK J" },
  { id: "KLP_J_10", doc_id: "KLP_J_10", nomor_absen: "10", nama_lengkap: "Emmanuella Nirindra Hanum S. J.", kelompok: "KELOMPOK J" },
  { id: "KLP_J_11", doc_id: "KLP_J_11", nomor_absen: "11", nama_lengkap: "Gabriella Vanessa Alvarisvia", kelompok: "KELOMPOK J" },
  { id: "KLP_J_12", doc_id: "KLP_J_12", nomor_absen: "12", nama_lengkap: "Gaudensius Kenzou Yoshitra", kelompok: "KELOMPOK J" },
  { id: "KLP_J_13", doc_id: "KLP_J_13", nomor_absen: "13", nama_lengkap: "Gracia Olivie Setiawan", kelompok: "KELOMPOK J" },
  { id: "KLP_J_14", doc_id: "KLP_J_14", nomor_absen: "14", nama_lengkap: "Ivandro Togu Evangelino Munthe", kelompok: "KELOMPOK J" },
  { id: "KLP_J_15", doc_id: "KLP_J_15", nomor_absen: "15", nama_lengkap: "Jacqueline Keiko Sugiharto", kelompok: "KELOMPOK J" },
  { id: "KLP_J_16", doc_id: "KLP_J_16", nomor_absen: "16", nama_lengkap: "Kenzo Noveriano Mamahi", kelompok: "KELOMPOK J" },
  { id: "KLP_J_17", doc_id: "KLP_J_17", nomor_absen: "17", nama_lengkap: "Kornelius Justin Wesley Saputra", kelompok: "KELOMPOK J" },
  { id: "KLP_J_18", doc_id: "KLP_J_18", nomor_absen: "18", nama_lengkap: "Leonard Alfred Raissa", kelompok: "KELOMPOK J" },
  { id: "KLP_J_19", doc_id: "KLP_J_19", nomor_absen: "19", nama_lengkap: "Leonard Jasson Fabregas", kelompok: "KELOMPOK J" },
  { id: "KLP_J_20", doc_id: "KLP_J_20", nomor_absen: "20", nama_lengkap: "Maria Novena Putri Avila", kelompok: "KELOMPOK J" },
  { id: "KLP_J_21", doc_id: "KLP_J_21", nomor_absen: "21", nama_lengkap: "Mayline Kurniawan Satyalaksana", kelompok: "KELOMPOK J" },
  { id: "KLP_J_22", doc_id: "KLP_J_22", nomor_absen: "22", nama_lengkap: "Michaella Evelyn Arnov Vienz", kelompok: "KELOMPOK J" },
  { id: "KLP_J_23", doc_id: "KLP_J_23", nomor_absen: "23", nama_lengkap: "Michelle Frenlie Gunawan", kelompok: "KELOMPOK J" },
  { id: "KLP_J_24", doc_id: "KLP_J_24", nomor_absen: "24", nama_lengkap: "Nelson Silvano Richado", kelompok: "KELOMPOK J" },
  { id: "KLP_J_25", doc_id: "KLP_J_25", nomor_absen: "25", nama_lengkap: "Nico Andrean Pramana", kelompok: "KELOMPOK J" },
  { id: "KLP_J_26", doc_id: "KLP_J_26", nomor_absen: "26", nama_lengkap: "R. Julio Evander Cawsar S", kelompok: "KELOMPOK J" },
  { id: "KLP_J_27", doc_id: "KLP_J_27", nomor_absen: "27", nama_lengkap: "Samantha Hwandita Wijaya", kelompok: "KELOMPOK J" },
  { id: "KLP_J_28", doc_id: "KLP_J_28", nomor_absen: "28", nama_lengkap: "Theodore Ivan Deo Rafael", kelompok: "KELOMPOK J" },
  { id: "KLP_J_29", doc_id: "KLP_J_29", nomor_absen: "29", nama_lengkap: "Tristan Timothy Gultom", kelompok: "KELOMPOK J" },
  { id: "KLP_J_30", doc_id: "KLP_J_30", nomor_absen: "30", nama_lengkap: "Vincentia Nataneila Garnetta Yuztin", kelompok: "KELOMPOK J" },
  { id: "KLP_J_31", doc_id: "KLP_J_31", nomor_absen: "31", nama_lengkap: "Wuli Tjunjungwangi", kelompok: "KELOMPOK J" },

  // ==================== KELOMPOK K (31 Siswa) ====================
  { id: "KLP_K_01", doc_id: "KLP_K_01", nomor_absen: "01", nama_lengkap: "Alice Agatha Putradharma", kelompok: "KELOMPOK K" },
  { id: "KLP_K_02", doc_id: "KLP_K_02", nomor_absen: "02", nama_lengkap: "Amelia Renata Harjito", kelompok: "KELOMPOK K" },
  { id: "KLP_K_03", doc_id: "KLP_K_03", nomor_absen: "03", nama_lengkap: "Athanasius Adven Kanugra", kelompok: "KELOMPOK K" },
  { id: "KLP_K_04", doc_id: "KLP_K_04", nomor_absen: "04", nama_lengkap: "Aurelia Stefanie", kelompok: "KELOMPOK K" },
  { id: "KLP_K_05", doc_id: "KLP_K_05", nomor_absen: "05", nama_lengkap: "Avelina Claudia Inri Sirumorang", kelompok: "KELOMPOK K" },
  { id: "KLP_K_06", doc_id: "KLP_K_06", nomor_absen: "06", nama_lengkap: "Benedict Nathan Santoso", kelompok: "KELOMPOK K" },
  { id: "KLP_K_07", doc_id: "KLP_K_07", nomor_absen: "07", nama_lengkap: "Bhryzha Orlanda Saputro", kelompok: "KELOMPOK K" },
  { id: "KLP_K_08", doc_id: "KLP_K_08", nomor_absen: "08", nama_lengkap: "Catherine Victoria Budiono", kelompok: "KELOMPOK K" },
  { id: "KLP_K_09", doc_id: "KLP_K_09", nomor_absen: "09", nama_lengkap: "Chaterine Miracle Chandra Dewi", kelompok: "KELOMPOK K" },
  { id: "KLP_K_10", doc_id: "KLP_K_10", nomor_absen: "10", nama_lengkap: "Cheryl Veronica Riyanto", kelompok: "KELOMPOK K" },
  { id: "KLP_K_11", doc_id: "KLP_K_11", nomor_absen: "11", nama_lengkap: "Cherylle Aniela Rimansah", kelompok: "KELOMPOK K" },
  { id: "KLP_K_12", doc_id: "KLP_K_12", nomor_absen: "12", nama_lengkap: "Cleotia Mersilia Sanvensto", kelompok: "KELOMPOK K" },
  { id: "KLP_K_13", doc_id: "KLP_K_13", nomor_absen: "13", nama_lengkap: "Dominicus Aditya Quai", kelompok: "KELOMPOK K" },
  { id: "KLP_K_14", doc_id: "KLP_K_14", nomor_absen: "14", nama_lengkap: "Gabriel Charissa Radanti", kelompok: "KELOMPOK K" },
  { id: "KLP_K_15", doc_id: "KLP_K_15", nomor_absen: "15", nama_lengkap: "Gabriel Ezra Gohi", kelompok: "KELOMPOK K" },
  { id: "KLP_K_16", doc_id: "KLP_K_16", nomor_absen: "16", nama_lengkap: "Gabriel Mateo Samuelson Hutapea", kelompok: "KELOMPOK K" },
  { id: "KLP_K_17", doc_id: "KLP_K_17", nomor_absen: "17", nama_lengkap: "Garnetta Lady Evangelista Siagian", kelompok: "KELOMPOK K" },
  { id: "KLP_K_18", doc_id: "KLP_K_18", nomor_absen: "18", nama_lengkap: "Gerardo Richie Narendra", kelompok: "KELOMPOK K" },
  { id: "KLP_K_19", doc_id: "KLP_K_19", nomor_absen: "19", nama_lengkap: "Jonathan William Prasetio", kelompok: "KELOMPOK K" },
  { id: "KLP_K_20", doc_id: "KLP_K_20", nomor_absen: "20", nama_lengkap: "Kevin Fabrizio Prabowo", kelompok: "KELOMPOK K" },
  { id: "KLP_K_21", doc_id: "KLP_K_21", nomor_absen: "21", nama_lengkap: "Louis Arthur Wibisono", kelompok: "KELOMPOK K" },
  { id: "KLP_K_22", doc_id: "KLP_K_22", nomor_absen: "22", nama_lengkap: "Maximillian Allan Javas", kelompok: "KELOMPOK K" },
  { id: "KLP_K_23", doc_id: "KLP_K_23", nomor_absen: "23", nama_lengkap: "Maximillian Hans Hadikusuma", kelompok: "KELOMPOK K" },
  { id: "KLP_K_24", doc_id: "KLP_K_24", nomor_absen: "24", nama_lengkap: "Michelle Clarista Cornelius", kelompok: "KELOMPOK K" },
  { id: "KLP_K_25", doc_id: "KLP_K_25", nomor_absen: "25", nama_lengkap: "Mikaela Casey Kurniawan", kelompok: "KELOMPOK K" },
  { id: "KLP_K_26", doc_id: "KLP_K_26", nomor_absen: "26", nama_lengkap: "Miranda Suwandy Teddy", kelompok: "KELOMPOK K" },
  { id: "KLP_K_27", doc_id: "KLP_K_27", nomor_absen: "27", nama_lengkap: "Rendianto Yohan", kelompok: "KELOMPOK K" },
  { id: "KLP_K_28", doc_id: "KLP_K_28", nomor_absen: "28", nama_lengkap: "Ringga Mesias Putra Wardhana", kelompok: "KELOMPOK K" },
  { id: "KLP_K_29", doc_id: "KLP_K_29", nomor_absen: "29", nama_lengkap: "Samuel Christian Gunawan", kelompok: "KELOMPOK K" },
  { id: "KLP_K_30", doc_id: "KLP_K_30", nomor_absen: "30", nama_lengkap: "Syailendra Mahardhika", kelompok: "KELOMPOK K" },
  { id: "KLP_K_31", doc_id: "KLP_K_31", nomor_absen: "31", nama_lengkap: "Vincent Hartanto", kelompok: "KELOMPOK K" }
];
